name: CD

run-name: Publish ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
      - '!v*'

jobs:
  gen:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref_name }}

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: SDK Path
        id: sdk
        run: echo "path=$(xcrun --sdk macosx --show-sdk-path)" >> $GITHUB_OUTPUT

      - name: Generate bindings
        run: |
          mise x -- bindgen \
            include/wrapper.h \
            --output src/bindings.rs \
            --allowlist-function 'CF(Dictionary|Array|String|Data|Number|Boolean|Release|Retain).*' \
            --allowlist-function 'Sec(Item|Key|Certificate|Identity).*' \
            --allowlist-var 'kSec.*' \
            --allowlist-var 'kCFBoolean(True|False)' \
            --allowlist-var 'kCFTypeDictionary(Key|Value)CallBacks' \
            --allowlist-type 'Sec.*' \
            -- \
            -isysroot "${{ steps.sdk.outputs.path }}"

      - name: Stage generated code
        run: git add --force .

      - name: Create tree from ecosystem directory
        id: tree
        run: |
          TREE=$(git write-tree --prefix=crate/)
          echo "TREE=${TREE}" >> $GITHUB_OUTPUT

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create orphan commit
        id: commit
        run: |
          COMMIT=$(git commit-tree ${{ steps.tree.outputs.TREE }} -m "chore: generate code")
          echo "COMMIT=${COMMIT}" >> $GITHUB_OUTPUT

      - name: Create release tag
        run: git tag v${{ github.ref_name }} ${{ steps.commit.outputs.COMMIT }}

      - name: Push gen commit
        run: git push --force origin ${{ steps.commit.outputs.COMMIT }}:refs/heads/gen

      - name: Push release tag
        shell: bash
        run: git push origin v${{ github.ref_name }}
